# Use postgres/example user/password credentials
version: '3.1'

services:

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    node:
        image: "node:8"
        user: "node"
        working_dir: /home/node/app
        environment:
          - NODE_ENV=production
        volumes:
          - ./app:/home/node/app
        ports:
          - 3000:3000
        expose:
          - "3000"
        command: "node app.js"
        links:
          - db
